export const services = [
  {
    id: "web",
    slug: "website",
    number: "01",
    title: "Websites & web apps",
    description: "Fast, conversion-focused websites and custom web apps that make your business easier to trust and easier to use.",
    price: "From ₦650,000",
    amount: 650000,
    deliverables: [
      "A responsive website or custom web application",
      "Clear, conversion-focused page structure",
      "Performance, accessibility and launch support",
    ],
  },
  {
    id: "mobile",
    slug: "mobileapp",
    number: "02",
    title: "Mobile app development",
    description: "Cross-platform mobile products for teams that need a thoughtful MVP or a reliable app their customers return to.",
    price: "From ₦1,500,000",
    amount: 1500000,
    deliverables: [
      "A cross-platform iOS and Android app",
      "Core product flows and API integration",
      "Testing, release preparation and handover",
    ],
  },
  {
    id: "design",
    slug: "uiux-design",
    number: "03",
    title: "UI/UX design",
    description: "Clear user flows, wireframes and polished interfaces that turn a complicated product into a simple experience.",
    price: "From ₦350,000",
    amount: 350000,
    deliverables: [
      "User flows and information architecture",
      "Wireframes for key screens",
      "A polished, reusable interface design",
    ],
  },
  {
    id: "analytics",
    slug: "data-analytics",
    number: "04",
    title: "Data analytics",
    description: "Dashboards, reporting and analysis that help you understand what is happening and decide what to do next.",
    price: "From ₦400,000",
    amount: 400000,
    deliverables: [
      "A review of your available data sources",
      "Useful dashboards and recurring reports",
      "Actionable findings for your team",
    ],
  },
  {
    id: "consultancy",
    slug: "consultancy",
    number: "05",
    title: "Consultancy & business development",
    description: "Practical product, technology and growth guidance for founders and teams making important decisions.",
    price: "From ₦150,000 / session",
    amount: 150000,
    deliverables: [
      "A focused discussion of your current challenge",
      "Practical product or technology recommendations",
      "Clear next steps for your team",
    ],
  },
  {
    id: "maintenance",
    slug: "maintenance-social-media",
    number: "06",
    title: "Maintenance & social media",
    description: "Ongoing technical care, content systems and social media support that keep your digital presence active.",
    price: "From ₦300,000 / month",
    amount: 300000,
    deliverables: [
      "Routine website updates and technical checks",
      "Content planning and publishing support",
      "Ongoing care for your digital presence",
    ],
  },
] as const;
