export const projectServices = [
  {
    id: "technology-strategy-advisory",
    slug: "technology-strategy-advisory",
    number: "01",
    name: "Technology Strategy & Advisory",
    nigeria: "₦500K – ₦2.5M",
    international: "$400 – $1,800",
    startingAmount: 500000,
    description: "Practical technology guidance for organizations evaluating investments, modernizing operations, or planning their next stage of growth.",
    deliverables: [
      "Review of business goals, current systems, and constraints",
      "Prioritized technology recommendations and options",
      "A practical roadmap with risks, owners, and next steps",
    ],
  },
  {
    id: "ict-it-leadership-consulting",
    slug: "ict-it-leadership-consulting",
    number: "02",
    name: "ICT / IT Leadership Consulting",
    nigeria: "₦750K – ₦3M / month",
    international: "$600 – $2,000 / month",
    startingAmount: 750000,
    description: "Experienced technology leadership for teams that need stronger IT operations, governance, delivery, or executive-level technology direction.",
    deliverables: [
      "Leadership priorities and operating model review",
      "Technology team, vendor, and service oversight",
      "Regular executive updates and delivery recommendations",
    ],
  },
  {
    id: "digital-transformation",
    slug: "digital-transformation",
    number: "03",
    name: "Digital Transformation",
    nigeria: "₦1M – ₦5M+",
    international: "$800 – $4,000+",
    startingAmount: 1000000,
    description: "A structured approach to improving processes and customer experiences with technology, from opportunity discovery through implementation.",
    deliverables: [
      "Current-state process and systems assessment",
      "Transformation opportunities ranked by impact",
      "Phased implementation roadmap and success measures",
    ],
  },
  {
    id: "software-architecture",
    slug: "software-architecture",
    number: "04",
    name: "Software Architecture",
    nigeria: "₦750K – ₦10M",
    international: "$600 – $8,000",
    startingAmount: 750000,
    description: "Architecture planning that helps software teams make sound decisions about system structure, integrations, scalability, and maintainability.",
    deliverables: [
      "Requirements and existing architecture review",
      "System design, integration, and data-flow documentation",
      "Technology trade-offs, risks, and implementation guidance",
    ],
  },
  {
    id: "web-application-development",
    slug: "web-application-development",
    number: "05",
    name: "Web Application Development",
    nigeria: "₦450K – ₦2M+",
    international: "$300 – $1,800+",
    startingAmount: 450000,
    description: "Responsive websites and web applications designed around your users, business goals, and the workflows your product needs to support.",
    deliverables: [
      "Responsive interface and agreed product workflows",
      "Backend or third-party integrations within the agreed scope",
      "Testing, deployment, and handover documentation",
    ],
  },
  {
    id: "mobile-application-development",
    slug: "mobile-application-development",
    number: "06",
    name: "Mobile Application Development",
    nigeria: "₦3M – ₦15M+",
    international: "$2,200 – $13,000+",
    startingAmount: 3000000,
    description: "Mobile applications shaped around clear user journeys, reliable integrations, and the features needed for a useful first release.",
    deliverables: [
      "iOS and Android app implementation based on the agreed scope",
      "API integration and core application workflows",
      "Device testing, release preparation, and handover",
    ],
  },
  {
    id: "product-design-ui-ux",
    slug: "product-design-ui-ux",
    number: "07",
    name: "Product Design / UI/UX",
    nigeria: "₦450K – ₦8M",
    international: "$300 – $6,200",
    startingAmount: 450000,
    description: "Product design that turns user needs and business goals into clear flows, accessible interfaces, and implementation-ready design systems.",
    deliverables: [
      "User journeys and information architecture",
      "Wireframes and high-fidelity interface designs",
      "Reusable components and developer handoff notes",
    ],
  },
  {
    id: "backend-api-engineering",
    slug: "backend-api-engineering",
    number: "08",
    name: "Backend & API Engineering",
    nigeria: "₦2M – ₦10M+",
    international: "$1,800 – $8,000+",
    startingAmount: 2000000,
    description: "Backend systems and APIs built to support product workflows, integrations, secure data access, and dependable operations.",
    deliverables: [
      "API and data model design for agreed product requirements",
      "Backend implementation, integrations, and access controls",
      "Testing, deployment guidance, and technical documentation",
    ],
  },
  {
    id: "cloud-it-infrastructure",
    slug: "cloud-it-infrastructure",
    number: "09",
    name: "Cloud & IT Infrastructure",
    nigeria: "₦750K – ₦5M+",
    international: "$600 – $4,000+",
    startingAmount: 750000,
    description: "Cloud and infrastructure planning to improve reliability, security, deployment workflows, and operating visibility.",
    deliverables: [
      "Infrastructure and deployment environment assessment",
      "Cloud architecture and operational improvements",
      "Monitoring, access, backup, and handover recommendations",
    ],
  },
  {
    id: "cybersecurity-it-security-assessment",
    slug: "cybersecurity-it-security-assessment",
    number: "10",
    name: "Cybersecurity / IT Security Assessment",
    nigeria: "₦500K – ₦3M+",
    international: "$400 – $2,200+",
    startingAmount: 500000,
    description: "A scoped review of security practices and technology risks, with prioritized recommendations to improve organizational resilience.",
    deliverables: [
      "Assessment of agreed systems, policies, and access practices",
      "Risk findings prioritized by severity and business impact",
      "Remediation recommendations and follow-up actions",
    ],
  },
  {
    id: "data-analytics-bi",
    slug: "data-analytics-bi",
    number: "11",
    name: "Data Analytics & BI",
    nigeria: "₦500K – ₦3M",
    international: "$400 – $2,000",
    startingAmount: 500000,
    description: "Analytics and business intelligence that organize useful data into reporting and dashboards teams can use to make decisions.",
    deliverables: [
      "Review of available data sources and reporting needs",
      "Data preparation and agreed dashboard or reports",
      "Metric definitions and recommendations for ongoing use",
    ],
  },
  {
    id: "ai-business-automation",
    slug: "ai-business-automation",
    number: "12",
    name: "AI & Business Automation",
    nigeria: "₦1M – ₦7.5M+",
    international: "$800 – $6,000+",
    startingAmount: 1000000,
    description: "Automation and applied AI solutions for reducing repetitive work and improving the speed or consistency of business processes.",
    deliverables: [
      "Workflow discovery and automation suitability review",
      "An agreed automation or AI-enabled workflow",
      "Testing, operational safeguards, and usage guidance",
    ],
  },
  {
    id: "project-technology-management",
    slug: "project-technology-management",
    number: "13",
    name: "Project / Technology Management",
    nigeria: "₦400k – ₦1.5M / month",
    international: "$300 – $1,000 / month",
    startingAmount: 400000,
    description: "Hands-on coordination for technology projects, aligning stakeholders, delivery plans, risks, and progress toward agreed outcomes.",
    deliverables: [
      "Project plan, milestones, and delivery priorities",
      "Stakeholder coordination and progress reporting",
      "Risk tracking and support resolving delivery blockers",
    ],
  },
  {
    id: "it-coaching-executive-technology-training",
    slug: "it-coaching-executive-technology-training",
    number: "14",
    name: "IT Coaching / Executive Technology Training",
    nigeria: "₦100K – ₦300K / session",
    international: "$80 – $250 / session",
    startingAmount: 100000,
    description: "Practical one-to-one coaching or executive sessions tailored to the technology topics and decisions you need to understand.",
    deliverables: [
      "A session agenda shaped around your goals",
      "Clear explanations and guided discussion of selected topics",
      "Takeaways and recommended next steps",
    ],
  },
  {
    id: "technical-due-diligence-it-audit",
    slug: "technical-due-diligence-it-audit",
    number: "15",
    name: "Technical Due Diligence / IT Audit",
    nigeria: "₦500K – ₦2.5M",
    international: "$400 – $2,100",
    startingAmount: 500000,
    description: "An independent review of technology, systems, and delivery risks to support investment, procurement, or operational decisions.",
    deliverables: [
      "Review of agreed architecture, systems, and technology practices",
      "Findings on risks, maintainability, and operational readiness",
      "A concise report with prioritized recommendations",
    ],
  },
] as const;